<h1>pandas</h1>

<big>Series</big>

In [2]:
import pandas as pd
import numpy as np

In [3]:
SeriesVariable = np.random.randint(1,10,10)

In [10]:
print(SeriesVariable)
Series1 = pd.Series(SeriesVariable)
Series1

[7 9 3 7 1 1 1 7 6 1]


0    7
1    9
2    3
3    7
4    1
5    1
6    1
7    7
8    6
9    1
dtype: int32

In [11]:
type(Series1)

pandas.core.series.Series

In [12]:
pd.Series([])

Series([], dtype: float64)

In [16]:
SeriesVariable1 = np.random.randint(1,10,10)
print(SeriesVariable1)
Series2 = pd.Series(SeriesVariable1,index=["a","b","c","d","e","f","g","h","i","j"],dtype=float,name="untitle")
Series2

[6 3 2 1 6 3 2 2 3 4]


a    6.0
b    3.0
c    2.0
d    1.0
e    6.0
f    3.0
g    2.0
h    2.0
i    3.0
j    4.0
Name: untitle, dtype: float64

In [17]:
dic = pd.Series({
    "a":1,"b":2
})

In [18]:
dic

a    1
b    2
dtype: int64

In [19]:
dic[1]

2

In [21]:
dic[0:2]

a    1
b    2
dtype: int64

In [22]:
min(SeriesVariable1)

1

In [23]:
max(SeriesVariable1)

6

In [24]:
SeriesVariable1[3<SeriesVariable1]

array([6, 6, 4])

In [25]:
SeriesVariable1+SeriesVariable1

array([12,  6,  4,  2, 12,  6,  4,  4,  6,  8])

In [26]:
import pandas as pd

In [33]:
serriesArray = np.random.randint(1,10,10)
SerriesIndex = np.random.randint(11,20,10)
Series1 = pd.Series(serriesArray,name="untitle",index=SerriesIndex,dtype=float)
Series1

19    3.0
15    8.0
18    7.0
18    5.0
11    7.0
14    9.0
12    1.0
16    4.0
17    4.0
15    3.0
Name: untitle, dtype: float64

In [37]:
print(Series1>4)

19    False
15     True
18     True
18     True
11     True
14     True
12    False
16    False
17    False
15    False
Name: untitle, dtype: bool


In [39]:
Series1+Series1

19     6.0
15    16.0
18    14.0
18    10.0
11    14.0
14    18.0
12     2.0
16     8.0
17     8.0
15     6.0
Name: untitle, dtype: float64

In [42]:
pd.Series([])

Series([], dtype: float64)

In [44]:
dic = pd.Series({
    "a":1,"b":2
})
dic

a    1
b    2
dtype: int64